name = "mercora-revenue-retention"
app_id = "fba1cc06-4c70-4f4c-92a7-f24878ebeeaf"
app_url = "ba9ba428-78e2-4e6e-ac79-8a6dfe44fc99"
team_id = "a2b65f47-9f49-4d2f-a9be-0c673a76998a"
team_name = "Victor Nogueira's Team"
